const themes = [
    {
      "color-scheme": "light",
      "primary": "#570df8",
      "primary-content": "#ffffff",
      "secondary": "#f000b8",
      "accent": "#37cdbe",
      "neutral": "#3d4451",
      "base-100": "#ffffff",
      "info": "#3abff8",
      "success": "#36d399",
      "warning": "#fbbd23",
      "error": "#f87272",
      "theme": "default"
    },
    {
      "color-scheme": "dark",
      "primary": "#661AE6",
      "primary-content": "#ffffff",
      "secondary": "#D926AA",
      "accent": "#1FB2A5",
      "neutral": "#191D24",
      "base-100": "#2A303C",
      "info": "#3ABFF8",
      "success": "#36D399",
      "warning": "#FBBD23",
      "error": "#F87272",
      "theme": "dark"
    },
    {
      "color-scheme": "light",
      "primary": "#65c3c8",
      "primary-content": "#ffffff",
      "secondary": "#ef9fbc",
      "accent": "#eeaf3a",
      "neutral": "#291334",
      "base-100": "#faf7f5",
      "info": "#3abff8",
      "success": "#36d399",
      "warning": "#fbbd23",
      "error": "#f87272",
      "theme": "cupcake"
    },
    {
      "color-scheme": "dark",
      "primary": "#6419e6",
      "primary-content": "#ffffff",
      "secondary": "#d926a9",
      "accent": "#1fb2a6",
      "neutral": "#2a323c",
      "base-100": "#1d232a",
      "info": "#3abff8",
      "success": "#36d399",
      "warning": "#fbbd23",
      "error": "#f87272",
      "theme": "cyberpunk"
    },
    {
      "color-scheme": "dark",
      "primary": "#ff79c6",
      "primary-content": "#ffffff",
      "secondary": "#bd93f9",
      "accent": "#ffb86c",
      "neutral": "#414558",
      "base-100": "#282a36",
      "info": "#8be9fd",
      "success": "#50fa7b",
      "warning": "#f1fa8c",
      "error": "#ff5555",
      "theme": "dracula"
    },
    {
      "color-scheme": "light",
      "primary": "#4b6bfb",
      "primary-content": "#ffffff",
      "secondary": "#7b92b2",
      "accent": "#67cba0",
      "neutral": "#181a2a",
      "base-100": "#ffffff",
      "info": "#3abff8",
      "success": "#36d399",
      "warning": "#fbbd23",
      "error": "#f87272",
      "theme": "corporate"
    },
    {
      "color-scheme": "dark",
      "primary": "#793ef9",
      "primary-content": "#ffffff",
      "secondary": "#f9d72f",
      "accent": "#ea5234",
      "neutral": "#110e0e",
      "base-100": "#171212",
      "info": "#3abff8",
      "success": "#36d399",
      "warning": "#fbbd23",
      "error": "#f87272",
      "theme": "synthwave"
    },
    {
      "color-scheme": "dark",
      "primary": "#1eb854",
      "primary-content": "#ffffff",
      "secondary": "#1fd65f",
      "accent": "#d99330",
      "neutral": "#110e0e",
      "base-100": "#171212",
      "info": "#3abff8",
      "success": "#36d399",
      "warning": "#fbbd23",
      "error": "#f87272",
      "theme": "forest"
    },
    {
      "color-scheme": "light",
      "primary": "#d1c1d7",
      "primary-content": "#ffffff",
      "secondary": "#f6cbd1",
      "accent": "#b4e9d6",
      "neutral": "#70acc7",
      "base-100": "#ffffff",
      "info": "#3abff8",
      "success": "#36d399",
      "warning": "#fbbd23",
      "error": "#f87272",
      "theme": "pastel"
    },
    {
      "color-scheme": "light",
      "primary": "#641ae6",
      "primary-content": "#ffffff",
      "secondary": "#d926a9",
      "accent": "#1fb2a6",
      "neutral": "#1f2937",
      "base-100": "#ffffff",
      "info": "#3abff8",
      "success": "#36d399",
      "warning": "#fbbd23",
      "error": "#f87272",
      "theme": "fantasy"
    },
    {
      "color-scheme": "dark",
      "primary": "#38bdf8",
      "primary-content": "#ffffff",
      "secondary": "#818cf8",
      "accent": "#f471b5",
      "neutral": "#1e293b",
      "base-100": "#0f172a",
      "info": "#0ea5e9",
      "success": "#22c55e",
      "warning": "#f59e0b",
      "error": "#ef4444",
      "theme": "black"
    },
    {
      "color-scheme": "light",
      "primary": "#f97316",
      "primary-content": "#ffffff",
      "secondary": "#8b5cf6",
      "accent": "#14b8a6",
      "neutral": "#1f2937",
      "base-100": "#ffffff",
      "info": "#06b6d4",
      "success": "#22c55e",
      "warning": "#eab308",
      "error": "#ef4444",
      "theme": "autumn"
    },
    {
      "color-scheme": "light",
      "primary": "#be123c",
      "primary-content": "#ffffff",
      "secondary": "#f43f5e",
      "accent": "#f97316",
      "neutral": "#44403c",
      "base-100": "#fafaf9",
      "info": "#06b6d4",
      "success": "#16a34a",
      "warning": "#eab308",
      "error": "#dc2626",
      "theme": "valentine"
    },
    {
      "color-scheme": "dark",
      "primary": "#fbbf24",
      "primary-content": "#292524",
      "secondary": "#d97706",
      "accent": "#ea580c",
      "neutral": "#44403c",
      "base-100": "#292524",
      "info": "#0ea5e9",
      "success": "#22c55e",
      "warning": "#f59e0b",
      "error": "#ef4444",
      "theme": "retro"
    },
    {
      "color-scheme": "dark",
      "primary": "#0ea5e9",
      "primary-content": "#ffffff",
      "secondary": "#14b8a6",
      "accent": "#f97316",
      "neutral": "#374151",
      "base-100": "#1f2937",
      "info": "#06b6d4",
      "success": "#22c55e",
      "warning": "#f59e0b",
      "error": "#ef4444",
      "theme": "aqua"
    }
  ];
  
  export default themes;